// Demo personas for the web demo and the CLI e2e.
//
// Here the script plays two roles. As the HOLDER it creates each persona's holder secret and an
// IssuanceRequest (commitment only). As the ISSUER it signs through issueFromRequest, which never
// sees the secret. The holder secrets are then written to the output next to the credentials so
// anyone can replay the demo: they are PUBLIC BY DESIGN and marked "demoOnly": true. A real holder
// app keeps its secret on the device and sends only the IssuanceRequest.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  createHolderSecret,
  createIssuanceRequest,
  holderSecretToHex,
  issuerKeyPairFromHex,
  type CredentialDocument,
  type CredentialSubject,
  type IssuanceRequest,
} from '@stateproof/core';
import type { IssuerKeyPair } from '@stateproof/contract';
import { REPO_ROOT, findIssuer, issuerSecretHex, loadRegistry, type IssuerEntry, type IssuerRegistry } from '../registry.js';
import { issueFromRequest } from './issue.js';

export const PERSONAS_SPEC_FILE = fileURLToPath(new URL('./personas.json', import.meta.url));
export const DEMO_PERSONAS_FILE = path.join(REPO_ROOT, 'config', 'demo-personas.v2.json');

export interface PersonaCredentialSpec {
  readonly issuer: string;
  readonly schema: string;
  readonly claims: CredentialSubject;
}

export interface PersonaSpec {
  readonly id: string;
  readonly role: string;
  readonly name: string;
  readonly birthDate: string;
  readonly credentials: readonly PersonaCredentialSpec[];
}

export interface PersonasSpecFile {
  readonly validity: { readonly issuedAt: string; readonly expiresAt: string };
  readonly personas: readonly PersonaSpec[];
}

export interface PersonaCredential {
  readonly issuanceRequest: IssuanceRequest;
  readonly credential: CredentialDocument;
}

export interface PersonaBundle {
  readonly id: string;
  readonly role: string;
  readonly name: string;
  readonly birthDate: string;
  // Demo only: a real holder secret never leaves the holder's device.
  readonly holderSecret: string;
  readonly credentials: readonly PersonaCredential[];
}

export interface DemoPersonasFile {
  readonly $comment: string;
  readonly format: 'jobproof-demo-personas/v2';
  readonly demoOnly: true;
  readonly generatedAt: string;
  readonly issuers: readonly { readonly id: string; readonly schema: string; readonly epoch: number }[];
  readonly personas: readonly PersonaBundle[];
}

export type KeyLookup = (entry: IssuerEntry) => IssuerKeyPair;

export const envKeyLookup: KeyLookup = (entry) => issuerKeyPairFromHex(issuerSecretHex(entry));

export const loadPersonaSpec = async (file: string = PERSONAS_SPEC_FILE): Promise<PersonasSpecFile> =>
  JSON.parse(await readFile(file, 'utf8')) as PersonasSpecFile;

export const buildPersonas = async (
  registry: IssuerRegistry,
  spec: PersonasSpecFile,
  keys: KeyLookup,
  now: Date = new Date(),
): Promise<DemoPersonasFile> => {
  const personas: PersonaBundle[] = [];
  const used = new Map<string, IssuerEntry>();
  for (const persona of spec.personas) {
    // Holder role: one secret per person, a fresh issuance request per credential.
    const holderSecret = createHolderSecret();
    const credentials: PersonaCredential[] = [];
    for (const c of persona.credentials) {
      const issuer = findIssuer(registry, c.issuer);
      if (issuer.schema !== c.schema) throw new Error(`${persona.id}: ${c.issuer} issues ${issuer.schema}, not ${c.schema}`);
      used.set(issuer.id, issuer);
      const issuanceRequest = createIssuanceRequest(c.schema, holderSecret);
      // Issuer role: only the request (commitment) and the checked facts cross this line.
      const credential = await issueFromRequest({
        issuer,
        keyPair: keys(issuer),
        request: issuanceRequest,
        subject: { name: persona.name, birthDate: persona.birthDate, claims: c.claims },
        issuedAt: spec.validity.issuedAt,
        expiresAt: spec.validity.expiresAt,
      });
      credentials.push({ issuanceRequest, credential });
    }
    personas.push({
      id: persona.id,
      role: persona.role,
      name: persona.name,
      birthDate: persona.birthDate,
      holderSecret: holderSecretToHex(holderSecret),
      credentials,
    });
  }
  return {
    $comment:
      'DEMO ONLY. Fictional people. The holder secrets below are public by design so anyone can replay the demo; a real holder secret never leaves the holder device and an issuer only ever receives the issuanceRequest (commitment). Generated by `npm run issue -w @stateproof/issuer -- personas`.',
    format: 'jobproof-demo-personas/v2',
    demoOnly: true,
    generatedAt: now.toISOString(),
    issuers: [...used.values()].map((i) => ({ id: i.id, schema: i.schema, epoch: i.epoch })),
    personas,
  };
};

export const issuePersonas = async (outFile: string = DEMO_PERSONAS_FILE): Promise<string> => {
  const registry = await loadRegistry();
  const file = await buildPersonas(registry, await loadPersonaSpec(), envKeyLookup);
  await writeFile(outFile, `${JSON.stringify(file, null, 2)}\n`, 'utf8');
  const count = file.personas.reduce((n, p) => n + p.credentials.length, 0);
  return `Issued ${count} credentials for ${file.personas.length} personas -> ${path.relative(REPO_ROOT, outFile)}`;
};
